config/routes.rb
Rails.application.routes.draw do
  root 'file_stream#index'
  post 'file_stream', controller: :file_stream, action: :create, as: :filter_and_stream
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/file_stream_controller.rb
require 'faker'
class FileStreamController < ApplicationController
  def index
  end

  def create
    column_numbers = params[:column_numbers].to_s.split(',').map(&:to_i)
    send_stream(filename: "streamed_data.csv") do |stream|
      # TODO: it's time to read the XLSX file
      book = Spreadsheet.open # SUBMITED FILE
      book.worksheets.each do |current_worksheet|
        current_worksheet.each do |row|
          row_content = column_numbers.map{|t| row[column_number]}.join(",")
          stream.write "#{row_content}\n"
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/file_stream/index.html.erb
<h1 class="h1">Fill with information, it's time to stream data!</h1>
<hr />
<div class="card">
  <div class="card-body">
    <%= form_tag filter_and_stream_path, multipart: true do %>
      <div class="form-group">
        <%= label_tag :column_numbers, 'Column numbers' %>
        <%= text_field_tag :column_numbers, params[:column_numbers], placeholder: 'Column numbers separated by comma (0,1,4...)', class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= label_tag :xls_file, 'XLS File' %>
        <%= file_field_tag :xls_file, placeholder: 'XLS file with the content that will be extracted and streamed', class: 'form-control', required: true %>
      </div>
      <button type="submit" class="btn btn-primary">Filter and stream data</button>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stream::To::Small::Content</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>